# Generated by Django 2.0.3 on 2021-03-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='', verbose_name='pics')),
                ('name', models.TextField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
    ]
